import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Video App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body>
  <nav style={{ padding: 16, borderBottom: "1px solid #ccc" }}>
    <Link href="/" style={{ marginRight: 12 }}>Home</Link>
    <Link href="/login" style={{ marginRight: 12 }}>Login</Link>
    <Link href="/signUp" style={{ marginRight: 12 }}>SignUp</Link>
  </nav>

  <div style={{ padding: 24 }}>
    {children}
  </div>
</body>

    </html>
  );
}
